## Useful Numpy

Just useful numpy code

In [1]:
import numpy as np

### Convert array of indices to One-Hot encoded NumPy array

In [8]:
a = np.array([1,0,3]) # Sample 1 (a[0]) is class=2, sample 2 (a[1]) is class=0 and sample 3 (a[2]) is class=3

# b = array([[0,1,0,0], [1,0,0,0], [0,0,0,1]])

In [3]:
b = np.zeros((a.size, a.max() + 1))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Use of advanced numpy indexing. Instead of regular slicing, you can select just one column per row, so that you can assign values to just one column per row (the columns that matches the classes in "a")

In [7]:
print(a.size, len(a))
b[np.arange(a.size), a] = 1
b

3 3


array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [12]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

### Convert pandas dataframde to numpy array

In [14]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        'A': [np.nan, np.nan, np.nan, 0.1, 0.1, 0.1, 0.1],
        'B': [0.2, np.nan, 0.2, 0.2, 0.2, np.nan, np.nan],
        'C': [np.nan, 0.5, 0.5, np.nan, 0.5, 0.5, np.nan],
    },
    index=[1, 2, 3, 4, 5, 6, 7],
).rename_axis('ID')
df

A    B    C
ID               
1   NaN  0.2  NaN
2   NaN  NaN  0.5
3   NaN  0.2  0.5
4   0.1  0.2  NaN
5   0.1  0.2  0.5
6   0.1  NaN  0.5
7   0.1  NaN  NaN

You get the df.to_numpy() method for this

In [16]:
df.to_numpy()

array([[nan, 0.2, nan],
       [nan, nan, 0.5],
       [nan, 0.2, 0.5],
       [0.1, 0.2, nan],
       [0.1, 0.2, 0.5],
       [0.1, nan, 0.5],
       [0.1, nan, nan]])

There is not a direct conversion to torch from Pandas

In [23]:
import torch

torch.tensor(df.to_numpy(), dtype=torch.float32)

tensor([[   nan, 0.2000,    nan],
        [   nan,    nan, 0.5000],
        [   nan, 0.2000, 0.5000],
        [0.1000, 0.2000,    nan],
        [0.1000, 0.2000, 0.5000],
        [0.1000,    nan, 0.5000],
        [0.1000,    nan,    nan]])